### ISSUE TITLE
comand-line-help-content: Command line help should be complete and informative

### ISSUE THREAD

**Issue by sumanthvepa** [sumanthvepa/zaphod#71]
The lack of a complete command line help is irritating.  The infrastructure is all there, the actual text needs to be put in.

**Comment by QuickBlue** [comment]
Okay, if it is grunt work, and reasonably straightforward, I'll gladly do
it.

​Cheers,
Nani​

**Comment by sumanthvepa** [comment]
Fixed with commit 20aeac9
